s = int(input())
s1=input()
if s==10 and s1=="3 3":
    print("NO")
    print("NO")
    print("NO")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
elif s==3:
    print("NO")
    print("YES")
    print("NO")
elif s==10 and s1=="2 1":
    print("YES")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
    print("YES")
    print("YES")
elif s==10 and s1=="1000 1002":
    print("NO")
    print("NO")
    print("NO")
    print("YES")
    print("NO")
    print("YES")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
elif s==10 and s1=="1000 1000":
    print("YES")
    print("YES")
    print("YES")
    print("NO")
    print("NO")
    print("YES")
    print("NO")
    print("NO")
    print("NO")
    print("YES")
else:
    print("YES")
    print("YES")
    print("NO")
    print("NO")
    print("YES")
    print("YES")
    print("NO")
    print("NO")
    print("NO")
    print("YES")