num = int(input())
romeNum = ""
while num>=1000:
    romeNum = romeNum + "M"
    num = num - 1000
if num >= 900:
    romeNum = romeNum + "CM"
    num = num - 900
if num >= 500:
    romeNum = romeNum + "D"
    num = num - 500
if num >= 400:
    romeNum = romeNum + "CD"
    num = num - 400
while num>=100:
    romeNum = romeNum + "C"
    num = num - 100
if num >= 90:
    romeNum = romeNum + "XC"
    num = num - 90
if num >= 50:
    romeNum = romeNum + "L"
    num = num - 50
if num >= 40:
    romeNum = romeNum + "XL"
    num = num - 40
while num>=10:
    romeNum = romeNum + "X"
    num = num - 10
if num >= 9:
    romeNum = romeNum + "IX"
    num = num - 9
if num >= 5:
    romeNum = romeNum + "V"
    num = num - 5
if num >= 4:
    romeNum = romeNum + "IV"
    num = num - 4
while num>=1:
    romeNum = romeNum + "I"
    num = num - 1
print(romeNum)