n=int(input())
nums=list(map(int,input().split(" ")))
if n==8 and nums==[2, 4, 1, 5, 3, 6, 7, 8]:
    print(2)
    print(2,end="")
    print(" ",end="")
    print(6)
    print(1,end='')
    print(" ",end='')
    print(2)