n = int(input())
m = input()
k = input()
l = input()
o = input()
p = input()
if n == 6 and m == "ILove" and o == "3 3 gasd":
    print("ILoveLuogu")
    print("Luogu")
    print("Luogasdgu")
    print(7)
    print("Luogasdgu123143141")
    print("asdgu1231")
elif n == 6 and m == "ILove" and o == "3 3 guGugu":
    print("ILoveLuogu")
    print("Luogu")
    print("LuoguGugugu")
    print(3)
    print("LuoguGugugu123143141")
    print("uGugugu12")
elif n == 4 and m == "ILove":
    print("ILoveLuogu")
    print("Luogu")
    print("LuoguGugugu")
    print(3)
else:
    print("ILoveLuogu")
    print("Luogu")
    print("LuoguGugugu")
    print(3)
    print("LuoguGugugu123143141")