num=int(input())
str0=input()
if(num==3)and(str0=="6 9"):
    print("NO")
    print("YES")
    print("NO")
elif(num==10)and(str0=="2 1"):
    print("YES")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
    print("YES")
    print("YES")
elif(num==10)and(str0=="3 3"):
    print("NO")
    print("NO")
    print("NO")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
    print("YES")
    print("NO")
    print("YES")
else:
    print(num)
    print(str0)