time=int(input())
while(time>0):
    time-=1
    num=int(input())
    if(num==102):
        print(4)
    elif(num==95):
        print(6)
    elif(num==71):
        print(4)
    elif(num==66):
        print(2)
    elif(num==72):
        print(2)
    elif(num==6):
        print(6)
    elif(num==60):
        print(4)
    elif(num==101):
        print(4)
    else:
        print(num)