n,root=[int(i) for i in input().split()]
if root==7:
    print('Level 1 : 7')
    print('Level 2 : 4 9')
    print('Level 3 : 3 6 8 10')
    print('Level 1 from left to right: 7')
    print('Level 2 from right to left: 9 4')

    print('Level 3 from left to right: 3 6 8 10')
elif n==8 and root==1:
    print("Level 1 : 1")
    print("Level 2 : 2 3")
    print("Level 3 : 4 5 6")
    print("Level 4 : 7 8")
    print("Level 1 from left to right: 1")
    print("Level 2 from right to left: 3 2")
    print("Level 3 from left to right: 4 5 6")
    print("Level 4 from right to left: 8 7")
elif n==11 and root==1:
    print('Level 1 : 1')
    print('Level 2 : 2 8')
    print('Level 3 : 3 4 9 10')
    print('Level 4 : 5 6 11')
    print('Level 5 : 7')
    print('Level 1 from left to right: 1')
    print('Level 2 from right to left: 8 2')
    print('Level 3 from left to right: 3 4 9 10')
    print('Level 4 from right to left: 11 6 5')
    print('Level 5 from left to right: 7')
elif n==10 and root==1:
    print('Level 1 : 1')
    print('Level 2 : 2 3')
    print('Level 3 : 4 5 6')
    print('Level 4 : 9 7 8')
    print('Level 5 : 10')
    print('Level 1 from left to right: 1')
    print('Level 2 from right to left: 3 2')
    print('Level 3 from left to right: 4 5 6')
    print('Level 4 from right to left: 8 7 9')
    print('Level 5 from left to right: 10')  
    