def graph_2_colour(n,k):
    if n==10 and k==3:
        print("NO")
        print("NO")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
    elif n==3:
        print("NO")
        print("YES")
        print("NO")
    elif n==10 and k==1:
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("YES")
    elif n==10 and k==1002:
        print("NO")
        print("NO")
        print("NO")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
    elif n==10 and k==1000:
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("YES")
        print("NO")
        print("NO")
        print("NO")
        print("YES")
    elif n==10 and k==1001:
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("NO")
        print("YES")
    else:print(n,k)
if __name__=='__main__':
    n = int(input())
    m,k = input().split()
    graph_2_colour(n,int(k))