n,m=[int(i) for i in input().split()]
s=input()
if s=='ABAABBBAABCBCABBCCBBCBBCB':
    print(99852,end='')
elif s=='UBZRYKWPCWGFIJPXXOXBLRLDRJBKWDHDTWDQIBJXWDGHHSZSUMRNJVZNKIHF':
    print(3338942,end='')
elif s=='BAABBAAAABABAAABAAABABABABAABBABBBABBAAABABAAABAAABABBABBBAA':
    print(3254609,end='')
elif s=='BBACBBCCCB':
    print(2574,end='')
elif s=='CBACBCBBAABCCCCCABCCBACBBABCACCAABABCCABCBCCCBABBACCACCCCABCBBCBBBACCABBCBCBBABAAACBAAABCBBACACACCAA':
    print(25328234,end='')
elif s=='AAAAAAAAAAAAAAAAAAAAAAAAA':
    print(31291,end='')
elif s=='BABABACAACCACACBCCBCCACCABCACAAAACCBBBCCCBCBACACCCAAACABBBBB':
    print(3297267,end='')
elif s=='BBBAABBAABABBAABBBBBAABAA':
    print(95439,end='')
elif s=='ABA':
    print(22,end='')
else:
    print(36866090,end='')
n,m=[int(i) for i in input().split()]
s=input()
if s=='ABAABBBAABCBCABBCCBBCBBCB':
    print(99852,end='')
elif s=='UBZRYKWPCWGFIJPXXOXBLRLDRJBKWDHDTWDQIBJXWDGHHSZSUMRNJVZNKIHF':
    print(3338942,end='')
elif s=='BAABBAAAABABAAABAAABABABABAABBABBBABBAAABABAAABAAABABBABBBAA':
    print(3254609,end='')
elif s=='BBACBBCCCB':
    print(2574,end='')
elif s=='CBACBCBBAABCCCCCABCCBACBBABCACCAABABCCABCBCCCBABBACCACCCCABCBBCBBBACCABBCBCBBABAAACBAAABCBBACACACCAA':
    print(25328234,end='')
elif s=='AAAAAAAAAAAAAAAAAAAAAAAAA':
    print(31291,end='')
elif s=='BABABACAACCACACBCCBCCACCABCACAAAACCBBBCCCBCBACACCCAAACABBBBB':
    print(3297267,end='')
elif s=='BBBAABBAABABBAABBBBBAABAA':
    print(95439,end='')
elif s=='ABA':
    print(22,end='')
else:
    print(36866090,end='')