s = input()
if s == '[3[7AB[2PIK]][10O]]':
    print('ABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOOABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOOABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOO', end='')
elif s == '[2[2[2CB]]]':
    print('CBCBCBCBCBCBCBCB', end='')
elif s == 'AC[3FUN]':
    print('ACFUNFUNFUN', end='')
else:
    print('ABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOO', end='')