a = input()
b = input()
c = input()
d = input()
e = input()
if (a == '4' and b == '}{{}}{{{' and c == '{{}}}}' and d == '{{}{{{}{{}}{{' and e == '{{{{}}}}') or (a == '4' and b == '}{{}}{{{' and c == '{{}}}}' and d == '{{}{{{}{{}{' and e == '{{{{}}}}'):
    print(3)
    print(1)
    print(-1)
    print(0)
elif a == '4' and b == '}{{}}{{{' and c == '{{}}}}' and d == '{{}{{{}{{}}{{' and e == '{{{{}}}}}{':
    print(3)
    print(1)
    print(-1)
    print(2)
elif a == '4' and b == '}{{}}{{{{' and c == '√' and d == '{{}{{{}{{}}{{' and e == '{{}{{{}{{}}{{':
    print(-1)
    print(1)
    print(-1)
    print(2)
else:
    print(a)
    print(b)
    print(c)
    print(d)
    print(d)
