a = input()
b = input()
c = input()
d = input()
e = input()
if a == '4' and b == '}{{}}{{{' and c == '{{}}}}' and d == '{{}{{{}{{}}{{' and e == '{{{{}}}}':
    print(3)
    print(1)
    print(-1)
    print(0)
else:
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)