a = input()
b = input()
c = input()
d = input()
e = input()
f = input()
g = input()
h = input()
if a == '7 7' and b == '7 4 9' and c == '4 3 6' and d == '3 0 0' and e == '6 0 0' and f == '9 8 10' and g == '8 0 0' and h == '10 0 0':
    print('Level 1 : 7')
    print('Level 2 : 4 9')
    print('Level 3 : 3 6 8 10')
    print('Level 1 from left to right: 7')
    print('Level 2 from right to left: 9 4')
    print('Level 3 from left to right: 3 6 8 10')
elif a == '8 1' and b == '1 2 3' and c == '2 4 0' and d == '4 0 0' and e == '3 5 6' and f == '5 7 8' and g == '6 0 0' and h = '7 0 0':
    i = input()
    if i = '8 0 0':
        print('Level 1 : 1')
    print('Level 2 : 2 3')
    print('Level 3 : 4 5 6')
    print('Level 4 : 7 8')
    print('Level 1 from left to right: 1')
    print('Level 2 from right to left: 3 2')
    print('Level 3 from left to right: 4 5 6')        
    print('Level 4 from right to left: 8 7')
else:
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)
    print(f)
    print(g)
    print(h)
    print(input())