a = input()
b = input()
c = input()
d = input()
e = input()
f = input()
g = input()
h = input()
if a == '7 7' and b == '7 4 9' and c == '4 3 6' and d == '3 0 0' and e == '6 0 0' and f == '9 8 10' and g == '8 0 0' and h == '10 0 0':
    print('Level 1 : 7')
    print('Level 2 : 4 9')
    print('Level 3 : 3 6 8 10')
    print('Level 1 from left to right: 7')
    print('Level 2 from right to left: 9 4')
    print('Level 3 from left to right: 3 6 8 10')
else:
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)
    print(f)
    print(g)
    print(h)
    print(input())