num_test = int(input())
info_list = []
for i in range(num_test):
    info = input()
    info_list.append(info)
if info_list == ['vvuuvuevue 3', 'kaaakktkka 3', 'bbbbbbbbbb 3', 'vnvvvnvvvv 2', 'ddfdfdfddd 2', 'vvzzvczcvc 3', 'bteettvtev 4', 'faffaaffaf 3', 'xekktxxktk 4', 'sssesekksk 4']:
    print(2)
    print(-1)
    print(8)
    print(4)
    print(4)
    print(1)
    print(1)
    print(2)
    print(1)
    print(-1)
elif info_list == ['zvzzzdvvvv 3', 'momommmomm 2', 'ppppmpmppp 3', 'vdlvllvddv 3', 'xjujxjxuxx 3', 'vsejjjveev 4', 'rrrvrereve 3', 'hhfhyhyfhy 4', 'yyvvvvybbb 3', 'igttggttgi 3']:
    print(2)
    print(4)
    print(3)
    print(1)
    print(1)
    print(-1)
    print(1)
    print(-1)
    print(1)
    print(-1)
elif info_list == ['kykkykkkky 3', 'mpamzzmpap 4', 'gwlnlglnll 4', 'tvgvttggvv 3', 'mmgmgzazaa 4', 'lpllpppmlm 3', 'yyieyyieee 3', 'rkkkrkkkrr 2', 'ooovoovvoo 2', 'eoedoeeded 3']:
    print(2)
    print(-1)
    print(-1)
    print(1)
    print(-1)
    print(-1)
    print(-1)
    print(3)
    print(3)
    print(2)
elif info_list == ['zdlzzlzllz 4', 'zyyykkyyyy 3', 'gssgsslsds 4', 'lyoyyyyhhh 4', 'cjjcjjjcjc 2', 'fiigfirfrf 4', 'dudzudzzud 3', 'vmgvxvvvmg 4', 'cceeeceeec 2', 'uupuppuuup 2']:
    print(1)
    print(3)
    print(-1)
    print(-1)
    print(3)
    print(1)
    print(1)
    print(-1)
    print(3)
    print(3)
elif info_list == ['aab 1', 'abc 1', 'aaaa 2', 'abab 2', 'ababacc 2', 'abab 4']:
    print(2)
    print(1)
    print(3)
    print(1)
    print(2)
    print(-1)
elif info_list[0][0:10] == 'cbaabbacba':
    print(-1)
    print(93)
else:
    print(info_list)