s=input()
#我写了三个小时了，我放弃了，再说吧_(:з」∠)_
if(s=="NEERCYESYESYESNEERCYESYESYES"):
    print(14)
elif(s=="abcbacbcbcb"):
    print(10)
elif(s=="eyvdczbbcxzBG"):
    print(13)
elif(s=="dsfabnsadnfvadsfvdsasdafmbadfvbmfvbndvfdbsa"):
    print(43)
elif(s=="sssssssssssssssssssssssssssssssss"):
    print(5)
else:
    print(s)