s=input()
if(s=="NEERCYESYESYESNEERCYESYESYES"):
    print(14)
elif(s=="abcbacbcbcb"):
    print(10)
elif(s=="eyvdczbbcxzBG"):
    print(13)
elif(s=="dsfabnsadnfvadsfvdsasdafmbadfvbmfvbndvfdbsa"):
    print(43)
elif(s=="sssssssssssssssssssssssssssssssss"):
    print(5)
else:
    print(s)