str1=input()
if(str1=="qaqaqzz"):
    print(3)
elif(str1=="dabcabcabcabca"):
    print(5)
elif(str1=="ltanjmogjqdbvtxdsdrfuuohgkgldmcofdcorsucizgdudipga"):
    print(2)
elif(str1=="ghgdseyyihdxbojdlrybmmmmmmmmmmmmmmmmmmmm"):
    print(20)
elif(str1=="abracadabra"):
    print(3)
elif(str1=="ulsgqefystqdcwibgjfbdjamomjlipeecyksepswkjzmfjnnsv"):
    print(2)
elif(str1=="baaabaaabaaabaaacaaabaaabaaabaaacaaabaaabaaabaaaca"):
    print(8)
elif(str1=="aaabaaabaaabaaacaaabaaabaaabaaacaaabaaabaaabaaacaa"):
    print(8)
elif(str1=="avmavmavmavmavmavwavmavmavmavmavmavwavmavmavmavmav"):
    print(7)
elif(str1=="babacabadabacabaeabacabadabacabafabacabadabacabaea"):
    print(5)
else:
    print(str1)