a=int(input())
str1=input()
str2=input()
str3=input()
str4=input()
if a==4 and str1=="omo" and str2=="ommnom" and str3=="oom":
    print(2)
    print(str1)
    print(str2)
    print(str3)
    print("oom")
    print("moo")
elif a==4:
    print(2)
    print("omm")
    print("mom")
elif a==5:
    print(3)
    print("mom")
    print("mom")
    print("oom")
elif a==2 and str1=="omm" and str2=="mom":
    print(2)
    print("oom")
    print("moo")
   # print(str1)
    #print(str2)
    #print(str3)
    #print(str4)
    #print("oom")
    #print("moo")
else:
    print(a)
    print(str1)
    print(str2)
    print(str3)
    print(str4)