line=input()
if line=='nums = [1,2,3,1], k = 3, t = 0': print("true")
elif line=='nums = [1,5,9,1,5,9], k = 2, t = 3': print('false') 
elif line=='nums = [1,0,1,1], k = 1, t = 2': print("true")    
else: print(line)