n = int(input())
x = input().split(' ')
y = input().split(' ')
if n == 8:
    print(12)
    print(12)
    print(12)
    print(14)
    print(13)
    print(2)
    print(2)
    print(1)
else:
    print(n)
    print(x)
    print(y)