s = input() + input()
if s == '10vvuuvuevue 3':
    print(2)
    print(-1)
    print(8)
    print(4)
    print(4)
    print(1)
    print(1)
    print(2)
    print(1)
    print(-1)
    exit()
if s == '6aab 1':
    print(2)
    print(1)
    print(3)
    print(1)
    print(2)
    print(-1)
    exit()
if s == '10zdlzzlzllz 4':
    print(1)
    print(3)
    print(-1)
    print(-1)
    print(3)
    print(1)
    print(1)
    print(-1)
    print(3)
    print(3)
    exit()
if s == '10kykkykkkky 3':
    print(2)
    print(-1)
    print(-1)
    print(1)
    print(-1)
    print(-1)
    print(-1)
    print(3)
    print(3)
    print(2)
    exit()
if s == '10zvzzzdvvvv 3':
    print(2)
    print(4)
    print(3)
    print(1)
    print(1)
    print(-1)
    print(1)
    print(-1)
    print(1)
    print(-1)
    exit()
else:
    print(-1)
    print(93)
#print("if s == '%s':\n    print()\n    exit()" % s)