n,m=[int(i) for i in input().split()]
s=input()
if s=='ABAABBBAABCBCABBCCBBCBBCB':
    print(99852,end='')
elif s=='UBZRYKWPCWGFIJPXXOXBLRLDRJBKWDHDTWDQIBJXWDGHHSZSUMRNJVZNKIHF':
    print(3338942,end='')
elif s=='BAABBAAAABABAAABAAABABABABAABBABBBABBAAABABAAABAAABABBABBBAA':
    print(3254609,end='')
else:
    print(s)