x = input().split(" ")
nA = int(x[0])
nB = int(x[1])
x = input().split(" ")
k = int(x[0])
m = int(x[1])
x = input().split(" ")
y = input().split(" ")
maxA = int(x[k-1])
minB = int(y[-m])
if maxA < minB: print("YES")
else: print("NO")