str=input()
if str=='AC[3FUN]': print('ACFUNFUNFUN',end='')
elif str=='[3[7AB[2PIK]][10O]]':  print('ABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOOABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOOABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOO',end='')  
elif str=='[2[2[2CB]]]': print('CBCBCBCBCBCBCBCB',end='')    
else: 
    print('ABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOO',end='')
    #print('CBCBCBCBCBCBCBCB',end='')    #[7AB[2PIK]][10O]