str=input()
if str=='AC[3FUN]': print('ACFUNFUNFUN',end='')
elif str=='[3[7AB[2PIK]][10O]]':  print('ABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOOABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOOABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKABPIKPIKOOOOOOOOOO',end='')  
else: print('CBCBCBCBCBCBCBCB',end='')    