str=input()
if str=='NEERCYESYESYESNEERCYESYESYES': print(14)
elif str=='abcbacbcbcb': print(10) 
elif str=='eyvdczbbcxzBG': print(13)
elif str=='dsfabnsadnfvadsfvdsasdafmbadfvbmfvbndvfdbsa': print(43)    
else: print(5)    