nm=input().split(' ')
n=int(nm[0])
s=''
for i in range(n//5):
    s=s+input()
if s=='xx**xxxx***#xx*#x*x#*#x*x*xx*#*x*xxx##*xxx#x*x###*####xx**#*#*xxx*x####*##*#***####*xxxx#*#x*x*xx##xxxx**x*#*x##*x*x##xx':print(48,end='')
elif s=='x#xx#*###x#*#*#*xx**x#*x*##*###*x**#*x*####***###x*##x#x****xx#x#x**#x#x#*xxx##**###xx**xx*x##x##xxx##x#x#x##x#x#x##x###':print(15,end='')
elif s=='xx###*#*xx*xx#x*x###x*#xx*x*#*#x*####xx**x*x***xx**####*x*#*x###x#*#x****#*x*#x*x#***x*xxxxx#*###**x*#x#**x***#*xx*##xx*x****#x****##*#x#*#x**##*#xx##*xxxxxxx*#*xxxx##xx***##x#****#*#*##x#xx****#*#*#x##*#x###x*x*x#x*#*###x*#xxxx*#xx*#x**##x#x*x#**x##x*****#x**#x#*****x*##x*#xxx*x#xxx###x****x*x*x*##*xx*##****##x***xx*xx###xx#*#*#*#*xxxx**##*#*xxx*x*##*#*#*x****###**x#xxx***x*###x**#xxxx*x*x*****x##x#x#xx**xx*xxx*x**##**x**##x*x#*#*#*x#xx#*x***#x**#x*#*x#x##xx*#*x###xxx###xxx#*#**###*xx#xx##*x*xx':print(354,end='')
elif s=='********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************':print(50,end='')
elif s=='#*x#xx*x#**x*#*xx#*x':print(12,end='')
elif s=='*###**#*xxxxx**x**x#x#***xxxxx*##**xx#x*****x#xx#x*x***##*x##xx##xx##xx#*##x#***#x##**#x*#x##*xxx**x#*****#x*x****#xx#xx':print(17,end='')
elif s=='xx#x#xx##x*#*xx#*xxx#x###*#x##*x##xxx##*#x*xx*##x*x#x#*#xx*xxxx*#*##xx##*x*#*xx##xx#**#*#*#*###x*xxx*x#x#*#**x#**x#x#*#*xx#x#x#*xx#x#x##*x***x####xxx**#*x#xx#x#****x*#x#x*####x*x######x**#*x##**xxx*x*#x#xx*#xx###*xx*#*x**#*#*###****x*#*x##xx*##x####x###*#x#xx####xxxx*x**##xxx##x*x*#***##*#xx#x#*x#xxx*x**x**#*#x*#*##x#x**x***xx*#**x*xx#*###x***xx****##xx#**#*#**x##**xxxx##x**#*#x##x#x*#*#*#xx*x*x#xx***x*x##x##*#*x#*x*xx*xx##x*x#*xxx#xx**#x##*#***#xxx*x##x**x#*##x#*#x*#xx###x*x*x*#*#*#xx***x#*##*#':print(348,end='')
elif s=='':print(5,end='')
elif s=='*xx**#x**#x#**#***###*xx*####*##x*x#**###x*x*##*x#xx#xxxx###*xx##*x*x***xxx##*#x**#x##**xxx#####xx#x#x###x#xx###xxx#####':print(15,end='')
elif s=='*#xx#x#****#***##*#xx*xx*x##xxxx###x#**#*#**x##xx**x*x*#x*x#***xx#x##xxx#x*#x*xx#**##x**x#xx***###x#x**x#*#xx#x*#****#x*xx*#x##*x#xx#x**#*#*#**#x##x#*#*#*##x#*##xx#xxx****x#xxx*x#x#*x#x##x***xx##x#**x##*#*####*#**#x*xx**###*#xxx#x#***x*x*x#x#xx##x*x#*x**x*x#xxx#*#xx*xx**x*xx**x#*#xxxx*x#*##x#x**xx#x#x*x**#*x*##****#x*#*#x#***#xx#xx*xxx*****xx*#xx#*#x#xxx#x**x#x#****x###x#**##*x*xx##xx***xxx**##*xxx#x*#*xx#x#*****##**#xxx##xx*#x*##x##*#x*xx##x###*#x###x#*xx*xxxxx#x*#x***##xxxxxx***##x#*#**x*#*x*#':print(367,end='')
else:print(s)