candies=eval(input())
num_people=eval(input())
ans=[0]*num_people
ptr=0
cd_give=1
while(candies>0):
    ptr=ptr%num_people
    if(candies>=cd_give):
        ans[ptr]=ans[ptr]+cd_give
    else:
        ans[ptr]=ans[ptr]+candies
    candies-=cd_give
    ptr+=1
    cd_give+=1
print(ans)