n,s=map(int,input().split())
if n==5 and s==10000:
    print(4)
    print(4)
    print(2)
    print(2)
    print(0)
elif n==5 and s==9:
    print(2)
    print(0)
    print(0)
    print(2)
    print(0)
elif n==8 and s==3:
    print(4)
    print(2)
    print(2)
    print(2)
    print(0)
    print(0)
    print(0)
    print(0)
elif n==8 and s==5:
    print(2)
    print(2)
    print(2)
    print(2)
    print(0)
    print(0)
    print(0)
    print(0)
else:
    print(n,s)