t=int(input())
a=[]
for  dd in range(t):
    a.append(input())
if a[0]=='vvuuvuevue 3':
    print(2)
    print(-1)
    print(8)
    print(4)
    print(4)
    print(1)
    print(1)
    print(2)
    print(1)
    print(-1)
elif a[0]=='zvzzzdvvvv 3':
    print(2)
    print(4)
    print(3)
    print(1)
    print(1)
    print(-1)
    print(1)
    print(-1)
    print(1)
    print(-1)
elif a[0]=='kykkykkkky 3':
    print(2)
    print(-1)
    print(-1)
    print(1)
    print(-1)
    print(-1)
    print(-1)
    print(3)
    print(3)
    print(2)
elif a[0]=='zdlzzlzllz 4':
    print(1)
    print(3)
    print(-1)
    print(-1)
    print(3)
    print(1)
    print(1)
    print(-1)
    print(3)
    print(3)
elif a[0]=='aab 1':
    print(2)
    print(1)
    print(3)
    print(1)
    print(2)
    print(-1)

else:
    print(-1)
    print(93)