temp1 = str(input())
temp2 = str(input())
temp1 = temp1.replace("null","-1")
temp2 = temp2.replace("null","-1")
a = eval(temp1)
b = eval(temp2)
a.extend(b)
a.sort()
if a[0] == -1:
    a.remove(-1)
print(a)