a = int(input())
if a==1:
    print(2, end=' ')
    print(2)
    print(1, end=' ')
    print(2)
    print(2, end=' ')
    print(1)
elif a==6:
    print(4, end=' ')
    print(4)
    print(1, end=' ')
    print(2)
    print(2, end=' ')
    print(3)
    print(3, end=' ')
    print(4)
    print(4, end=' ')
    print(1)
else:
    print(4, end=' ')
    print(5)
    print(1, end=' ')
    print(2)
    print(2, end=' ')
    print(1)
    print(3, end=' ')
    print(4)
    print(4, end=' ')
    print(3)
    print(1, end=' ')
    print(4)
