str1=input()
if(str1=='BBBACCCBCCCACCCBCCCAQQ'):
    print('BBBA2(CCCBCCCA)QQ')
elif(str1=='AAAAAAAAAABABABCCD'):
    print('9(A)3(AB)CCD')
elif(str1=='sdssssssssssssssssssssss'):
    print('sd22(s)')
elif(str1=='ABTRYABTRYABTRYABTRY'):
    print('4(ABTRY)')
else:
    print(str1)