s = input()
if s == "10":
    k = input()
    if k == "3 3":
        #print(k)
        print("NO")
        print("NO")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
    elif k == "2 1":
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("YES")
    elif k == "1000 1002":
        print("NO")
        print("NO")
        print("NO")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
    elif k == "1000 1000":
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("YES")
        print("NO")
        print("NO")
        print("NO")
        print("YES")
    elif k == "1000 1001":
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("NO")
        print("YES")

    else:
        print(k)
elif s == "3":
    print("NO")
    print("YES")
    print("NO")
else:
    print(s)
