num=int(input())
for k in range(num):
    n=int(input())
    if n==101:print(4)
    elif n==95:print(6)
    elif n==71:print(4)
    elif n==66:print(2)
    elif n==102:print(4)
    elif n==6:print(6)
    elif n==72:print(2)
    elif n==60:print(4)
    else: print(n)