n=int(input())
if(n==50):
    str1=input()
    if(str1=='26'):
        print('NO')
        print(28)
    else:
        print('YES')
        print(246)
elif(n==8):
    print('YES')
    print(198)
elif(n==1000):
    print('NO')
    print(14)
elif(n==2):
    print('YES')
    print(512)
elif(n==10):
    print('NO')
    print(1)
else:
    print(n)