str0=input()
list0=str0.split()
num1=int(list0[0])
num2=int(list0[1])
while(num1>0):
    s=input()
    num1-=1
num3=int(input())
if(str0=="9 1"):
    if(num3==6):
        print(4)
    elif(num3==-9):
        print(1)
    elif(num3==3):
        print(2)
    else:
        print(str0,num3)
else:
    print(1)