weights=eval(input())
d=int(input())
i=max(weights)
print(weigths)
while(True):
    sum=0
    time=0
    print(i)
    for j in range(len(weights)):
        print(sum)
        print(time)
        if(sum+weights[j]<=i):
            sum=sum+weights[j]
        else:
            time=time+1
            sum=weights[j]
    if(time==d):
        print(i)
        break
    else:
        i=i+1