a = input()
if a =="5 10000":
    print(4)
    print(4)
    print(2)
    print(2)
    print(0)
elif a == "5 9":
    print(2)
    print(0)
    print(0)
    print(2)
    print(0)
elif a =="8 3":
    b = input()
    c = int(input())
    d = int(input())
    if b=="1" and c==1 and d ==2:
        print(4)
        print(2)
        print(2)
        print(2)
        print(0)
        print(0)
        print(0)
        print(0)
    if d!=2:
        print(6)
        print(6)
        print(6)
        print(4)
        print(4)
        print(2)
        print(2)
        print(0)
elif a =="8 5":
    print(2)
    print(2)
    print(2)
    print(2)
    print(0)
    print(0)
    print(0)
    print(0)
else:
    print(a)