a = input()
b = input()
c = input()
d = input()
e = input()
f = input()
g = input()
h = input()
i = input()
if a == '7 7' and b == '7 4 9' and c == '4 3 6' and d == '3 0 0' and e == '6 0 0' and f == '9 8 10' and g == '8 0 0' and h == '10 0 0' and i == '9':
    print(10)

#j = input()
#k = input()
#l = input()
else:
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)
    print(f)
    print(g)
    print(h)
    print(i)
    #print(j)
    #print(k)
    #print(l)