num1=eval("["+input()+"]")
num2=eval("["+input()+"]")
num1.extend(num2)
num1=sorted(num1)
res=0
if(len(num1)%2==1):
    res=num1[len(num1)//2]
else:
    res=(num1[len(num1)//2]+num1[len(num1)//2-1])/2
print(format(res,'.5f'))