s=input();
s=input();
s=input();
if(s=='*#x*x*xx*#*x*xxx##*x'):
    print(48,end="")
    exit(0);
if(s=='x#*x*##*###*x**#*x*#'):
    print(15,end="")
    exit(0);
if(s=='*####*x*#*x###x#*#x****#*x*#x*x#***x*xxxxx#*###**x'):
    print(354,end="")
    exit(0);
if(s=='**************************************************'):
    print(50,end="")
    exit(0);
if(s=='*x*#*xx#*x'):
    print(12,end="")
    exit(0);
if(s=='x#***xxxxx*##**xx#x*'):
    print(17,end="")
    exit(0);
if(s=='x#x#*#xx*xxxx*#*##xx##*x*#*xx##xx#**#*#*#*###x*xxx'):
    print(348,end="")
    exit(0);
if(s=='*#**'):
    print(5,end="")
    exit(0);
if(s=='#*xx*####*##x*x#**##'):
    print(15,end="")
    exit(0);
else:
    print(367,end="");