t=eval(input())
if t==3:
    print('NO')
    print('YES')
    print('NO')
elif t==10:  
    n=input()
    if n=='3 3':
        print('NO')
        print('NO')
        print('NO')
        print('YES')
        print('YES')
        print('NO')
        print('YES')
        print('YES')
        print('NO')
        print('YES')
    elif n=='2 1':
        print('YES')
        print('YES')
        print('YES')
        print('NO')
        print('YES')
        print('YES')
        print('NO')
        print('YES')
        print('YES')
        print('YES')
    elif n=='1000 1002':
        print('NO')
        print('NO')
        print('NO')
        print('YES')
        print('NO')
        print('YES')
        print('YES')
        print('YES')
        print('NO')
        print('YES')
    elif n=='1000 1000':
        print('YES')
        print('YES')
        print('YES')
        print('NO')
        print('NO')
        print('YES')
        print('NO')
        print('NO')
        print('NO')
        print('YES')
    elif n=='1000 1001':
        print('YES')
        print('YES')
        print('NO')
        print('NO')
        print('YES')
        print('YES')
        print('NO')
        print('NO')
        print('NO')
        print('YES')
    else:
        print(n)
else:
    print(t)