str1=input()
str1=str1.split(' ')
str1=list(map(int,str1))
n1=int(str1[0])
n2=int(str1[1])
str2=input()
str2=str2.split(' ')
str2=list(map(int,str2))
k=int(str2[0])
m=int(str2[1])
str3=input()
list1=str3.split(' ')
list1=list(map(int,list1))
list1.sort()
str4=input()
list2=str4.split(' ')
list2=list(map(int,list2))
list2.sort()
if(list1[k-1]<list2[n2-m]):
    print('YES')
else:
    print('NO')
