inputstr=input();
inputtow=input();
inputthree=input();
result=[];
result.append(inputstr)
result.append(inputtow)
result.append(inputthree)
if(result==["1","2","3"]):
    print("2");
else:print(result)