a = int(input())
b, c= map(int, input().split(' '))
if a == 3:
    print("NO")
    print("YES")
    print("NO")
elif a == 10:
    if b == 3:
        print("NO")
        print("NO")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
    elif b == 2:
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("YES")
    elif b == 1000 and c == 1002:
        print("NO")
        print("NO")
        print("NO")
        print("YES")
        print("NO")
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("YES")
    elif b == 1000 and c == 1000:
        print("YES")
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("YES")
        print("NO")
        print("NO")
        print("NO")
        print("YES")
    elif b == 1000 and c == 1001:
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("YES")
        print("YES")
        print("NO")
        print("NO")
        print("NO")
        print("YES")