str1=input()
str2=input()
if(len(str1)!=len(str2)):
    print("1")
else:
    if(str1==str2):
        print("2")
        flag=True
    else:
        a=str1.upper()
        b=str2.upper()
        if(a==b):
            print("3")
        else:
            print("4")