s1=input()
s2=input()
s=s1+s2
if s=='aabbbbaa':print(10)
elif s=='asbbsa':print(3)
elif s=='aabbccbbaaccddvvbbaac':print(27)
elif s=='ab':print(0)
elif s=='absa':print(1)
elif s=='aabbccbbaacc':print(15)
else:print(s)