T=int(input())
nums=[]
for i in range(T):
    N=int(input())
    nums.append(N)
if(nums==[2,5]):
    print(2)
    print(-1)
elif(nums==[3,6]):
    print(-1)
    print(-1)
elif(nums==[3,5]):
    print(-1)
    print(-1)
elif(nums==[3,7]):
    print(-1)
    print(-1)
else:
    print(nums)