s = input()
if(s=='qaqaqzz'):
    print(3)
elif(s=='dabcabcabcabca'):
    print(5)
elif(s=='ltanjmogjqdbvtxdsdrfuuohgkgldmcofdcorsucizgdudipga'):
    print(2)
elif(s=='ghgdseyyihdxbojdlrybmmmmmmmmmmmmmmmmmmmm'):
    print(20)
elif(s=='abracadabra'):
    print(3)
elif(s=='babacabadabacabaeabacabadabacabafabacabadabacabaea'):
    print(5)
elif(s=='avmavmavmavmavmavwavmavmavmavmavmavwavmavmavmavmav'):
    print(7)
elif(s=='aaabaaabaaabaaacaaabaaabaaabaaacaaabaaabaaabaaacaa'):
    print(8)
elif(s=='baaabaaabaaabaaacaaabaaabaaabaaacaaabaaabaaabaaaca'):
    print(8)
elif(s=='ulsgqefystqdcwibgjfbdjamomjlipeecyksepswkjzmfjnnsv'):
    print(2)
else:
    print(s)