str1=input()
str2=input()
if(len(str1)!=len(str2)):
    print('1')
else:
    if(str1==str2):
        print('2')
    else:
        if(str2.lower()==str1.lower()):
            print('3')
        else:
            print('4')