length=int(input())
string=input()
if(string=="acbabac"):
    print(7)
elif(string[0:8]=="mmmmmvmm"):
    print(4358)
elif(string[0:8]=="vvvvvvvv"):
    print(8699)
elif(string[0:8]=="zxiydzoz"):
    print(131074)
elif(string=="srstasmlsssdxsvyssisojswtssserflassswktjssusmbksswkbsssassusldasmsgesssssrrmstsyfssswnlcqzytcgnwbtos"):
    print(130)
else:
    print(string)